urbanopt/urbanopt-cli

- lib/uo_cli.rb
Adds a flag to get current CLI version printed to stdout.
I tried to branch this off of updates. Hopefully this can be merged to that branch quickly and without fuss. Let's see if I did my git-fu properly.
Addresses #10
> add version flag to cli

- lib/uo_cli.rb
This should have been changed before the updates branch was merged. Fortunately it was found quickly.
> change branch that files come from

- .travis.yml
> remove unused travis ci file

- Gemfile
- example_files/Gemfile
Addresses #20 
We don't need this at all. Make it go away.
> Remove dependency on simplecov

- lib/uo_cli.rb
Make permanent links for file downloads.
Should have done this before merging to master, I know.
> point file links to master

- example_files/runner.conf
- lib/uo_cli.rb
Addresses #25 
Requires #36 to have been merged already.
Includes some refactoring.
> Config file

- .github/pull_request_template.md
> Suggest that all PRs address an issue. Makes auto-changelog easy

- example_files/Gemfile
We will use whatever version the OpenStudio SDK uses.
> Remove separate dependency on os-standards

- .gitignore
- example_files/example_project.json
Remove residential buildings until HPXML process is implemented
Also add .ruby-version file to gitignore. This file tells rbenv how to set the developer's local ruby version.
> Remove residential buildings until HPXML process is implemented

- uo_cli.gemspec
- Specify Ruby version
- use pessimistic style for other dependencies
> Set Ruby version, allow pessimistic for other deps

- README.md
> Include new commands in readme

- lib/uo_cli.rb
- lib/uo_cli/version.rb
- Fix bug where I missed an `@` symbol.
- Clean up some low quality code, use File.basename instead of File.split
- Remove outdated comment
- bump version to 0.2.1
> Release fixes

- example_files/mappers/Baseline.rb
- spec/spec_files/test_directory/mappers/Baseline.rb
Copy baseline mapper from example-geojson-project repo
Enables hvac system types
> Use new baseline mapper file

- Gemfile
- lib/uo_cli.rb
- lib/uo_cli/version.rb
- spec/spec_helper.rb
- spec/uo_cli_spec.rb
- uo_cli.gemspec
New package for creating the CLI: Optimist. Optimist allows easy subcommands, which makes it easier to organize, display, read, and interact with the CLI.
> New CLI structure

- CHANGELOG.md
- lib/uo_cli.rb
- lib/uo_cli/version.rb
Don't look for reopt directory inside project directory until running a reopt simulation.
> Reopt dir hotfix

- example_files/scenario_comparison.html
- lib/uo_cli.rb
- spec/uo_cli_spec.rb
- Adds command for visualizing scenario results after post processing. 
- Adds html file to the example_file folder to generate output html file of results.
> Adds command for visualization of post processing results.

- example_files/mappers/Baseline.rb
- example_files/mappers/HighEfficiency.rb
- example_files/mappers/base_workflow.osw
> Adds new mappers

- Gemfile
- example_files/Gemfile
- example_files/mappers/Baseline.rb
- example_files/mappers/HighEfficiency.rb
- example_files/mappers/ThermalStorage.rb
- example_files/mappers/base_workflow.osw
- example_files/visualization/input_visualization_feature.html
- example_files/visualization/input_visualization_scenario.html
- lib/uo_cli.rb
- spec/uo_cli_spec.rb
- uo_cli.gemspec
Copy files from inside gem instead of downloading when making a new project folder.
> copy files from gem instead of downloading

- example_files/mappers/ThermalStorage.rb
- example_files/mappers/base_workflow.osw
updated the names of the ice storage measure
> updated ice storage measures names

- CONTRIBUTING.md
- LICENSE.md
- README.md
- Rakefile
- developer_nrel_key.rb
- example_files/mappers/Baseline.rb
- example_files/mappers/HighEfficiency.rb
- example_files/mappers/ThermalStorage.rb
- lib/uo_cli.rb
- lib/uo_cli/version.rb
- spec/spec_helper.rb
- spec/uo_cli_spec.rb
> adding tm symbol to files

- lib/uo_cli.rb
- spec/uo_cli_spec.rb
- Copies viz files from gem instead of downloading from github. Faster for users & easier for developers.
- Includes unit test
> Copy viz files

- lib/uo_cli.rb
- spec/uo_cli_spec.rb
Updates visualize tags to -f for scenario visualization and -s for feature visualization
> Updates visualize tags

- .github/pull_request_template.md
Update PR template to automatically close issues when PR gets merged
> update PR template to close issues automatically

- Gemfile
- example_files/Gemfile
- lib/uo_cli.rb
- spec/uo_cli_spec.rb
- uo_cli.gemspec
replaced the method to save feature results. the new methods are : 
save_json_report
save_csv_report
> New methods to save feature results

- spec/uo_cli_spec.rb
- Call the cli more authentically in the spec file
- relabel a test for clarity
- Clean up comments in tests
> Specfile updates

- Gemfile
- example_files/Gemfile
- example_files/eui_validation_schema.yaml
- example_files/validation_schema.yaml
- lib/uo_cli.rb
- spec/spec_files/out_of_bounds_validation.yaml
- spec/uo_cli_spec.rb
- uo_cli.gemspec
New cli command to validate eui results based on custom settings in `validation_schema.yaml`.
- Validation schema file will be added to new normal project directories (not if user specifies empty, though).
- Validation schema file is designed to be extendable to hold validation parameters for other outputs besides EUI.
- Yaml file format was chosen because it is easy to read like json, and allows comments whereas json doesn't.
TODO:
- write tests
- de-hardcode the path to the feature file
- set up a loop to check all features
> Eui validation

- Gemfile
- example_files/Gemfile
- example_files/mappers/base_workflow.osw
- lib/uo_cli.rb
- spec/uo_cli_spec.rb
- uo_cli.gemspec
Use new measures in reporting-gem
> Using des measures

- spec/spec_files/REopt_scenario.csv
- spec/spec_files/two_building_create_bar.csv
- spec/spec_files/two_building_floorspace.csv
- spec/spec_files/two_building_res.csv
- spec/spec_files/two_building_scenario.csv
- spec/uo_cli_spec.rb
Change buildings in the test suite to test on buildings that aren't so large.
> Speed up tests

- example_files/mappers/EvCharging.rb
This was causing a failure when I tested locally. This statement should not be present and is a typo.
> Remove unnessary statement

- example_files/mappers/Baseline.rb
re-added the multifamily options to the commercial_building_types list.
> re-added the multifamily options to the commercial_building_types list.

- CHANGELOG.md
- lib/uo_cli.rb
- spec/uo_cli_spec.rb
- uo_cli.gemspec
> remove pycall dependency

- LICENSE.md
- Rakefile
- example_files/mappers/Baseline.rb
- example_files/mappers/CreateBar.rb
- example_files/mappers/EvCharging.rb
- example_files/mappers/Floorspace.rb
- example_files/mappers/HighEfficiency.rb
- example_files/mappers/HighEfficiencyCreateBar.rb
- example_files/mappers/HighEfficiencyFloorspace.rb
- example_files/mappers/ThermalStorage.rb
- lib/uo_cli.rb
- lib/uo_cli/version.rb
- spec/spec_helper.rb
- spec/uo_cli_spec.rb
- Add paragraph to license
- Update to include 2021
> update license & copyright

- example_files/mappers/CreateBar.rb
- example_files/mappers/Floorspace.rb
- example_files/mappers/HighEfficiencyCreateBar.rb
- example_files/mappers/HighEfficiencyFloorspace.rb
Update requirement to reporting-gem instead of scenario-gem
> update internal requirement to reporting-gem

- .rubocop.yml
- uo_cli.gemspec
> update rubocop configs to v4

- example_files/mappers/Baseline.rb
> restore old res types

- example_files/mappers/Baseline.rb
- example_files/mappers/HighEfficiency.rb
- example_files/mappers/HighEfficiencyCreateBar.rb
- example_files/mappers/HighEfficiencyFloorspace.rb
> updating mappers to align with example project repo

- example_files/mappers/Baseline.rb
> fix BuildResidentialModel feature_id argument - JSON parsing issue

- example_files/mappers/Baseline.rb
> add load-flexibility dependency to baseline mapper

- example_files/visualization/input_visualization_feature.html
- example_files/visualization/input_visualization_scenario.html
> fix visualizations

- example_files/mappers/Baseline.rb
Update the mapping of Laboratory model to the new developed Laboratory prototype for ASHRAE 90.1
> Utilize ASHRAE 90.1 Laboratory prototype model

- example_files/mappers/Baseline.rb
- example_files/mappers/CreateBar.rb
- example_files/mappers/Floorspace.rb
- example_files/mappers/createbar_workflow.osw
- example_files/mappers/floorspace_workflow.osw
add missing feature location arguments to Floorspace .rb  & floorspace_workflow.osw and CreateBar.rb & createbar_workflow.osw
> add missing feature location arguments to Floorspace and CreateBar workflows

- lib/uo_cli.rb
> fix looking for sims run

- example_files/visualization/input_visualization_feature.html
- example_files/visualization/input_visualization_scenario.html
Fixes #278 
Also fixes natural gas not added to NET total on visualization graphs (feature comparison only)
> fixing visualization bugs when no reopt ts are not in results

- example_files/reopt/base_assumptions.json
- example_files/reopt/multiPV_assumptions.json
Accesses the reopt `off_grid_flag` when post-processing
> feat: add `off_grid_flag` key to reopt call

- CHANGELOG.md
- Rakefile
- example_files/mappers/Baseline.rb
- example_files/mappers/CreateBar.rb
- example_files/mappers/EvCharging.rb
- example_files/mappers/FlexibleHotWater.rb
- example_files/mappers/Floorspace.rb
- example_files/mappers/HighEfficiency.rb
- example_files/mappers/HighEfficiencyCreateBar.rb
- example_files/mappers/HighEfficiencyFloorspace.rb
- example_files/mappers/ThermalStorage.rb
- lib/uo_cli.rb
- lib/uo_cli/version.rb
- spec/spec_helper.rb
- spec/uo_cli_spec.rb
> updating copyrights for 2022

- lib/uo_cli.rb
- spec/spec_helper.rb
- spec/uo_cli_spec.rb
This is some comment deletion and formatting and I cleaned up the `opendss` test a bit.
> Suuuuuper minor formatting

- example_files/opendss/electrical_database.json
- example_files/opendss/example_config.json
- lib/uo_cli.rb
> potential fixes for opendss issues

- .gitignore
- Gemfile
- example_files/Gemfile
- example_files/example_project.json
- example_files/example_project_combined.json
- example_files/example_project_with_PV.json
- example_files/example_project_with_electric_network.json
- example_files/example_project_with_streets.json
- example_files/mappers/Baseline.rb
- example_files/validation_schema.yaml
- example_files/visualization/input_visualization_feature.html
- example_files/visualization/input_visualization_scenario.html
- lib/uo_cli.rb
- uo_cli.gemspec
updated example_files/mappers/Baseline.rb  and example_files/example_project_combined.json
[description here]
> added emissions calculations capability:

- lib/uo_cli.rb
- spec/uo_cli_spec.rb
- Update opendss call to use ditto_reader_cli installed with `uo install_python` command
- Follow rubocop suggestions
- Clean up
> Opendss changes

- scripts/setup-env.bat
> use quotes for usernames with spaces in them

- lib/uo_cli.rb
> install all mappers at project_dir creation

- example_files/Gemfile
> pin addressable dependency to resolve unicode_normalize error

- CHANGELOG.md
- Gemfile
- example_files/Gemfile
- lib/uo_cli/version.rb
> pin dependency and prep version 0.9.3

- example_files/python_deps/dependencies.json
Upgrade GMT version to 0.5.0 to pick up new release that can simulate DES models again
> Update gmt version

- lib/uo_cli.rb
- spec/uo_cli_spec.rb
Prepare a stable, consistent api
> Update CLI sub-commands to be consistent across commands

- .github/workflows/nightly_ci_build.yml
- example_files/python_deps/dependencies.json
- lib/uo_cli.rb
- spec/uo_cli_spec.rb
There were version conflicts among dependencies of our Python dependencies. Those projects need to relax their version requirements so they will all work together. This picks up the new versions that have relaxed requirements.
> Update python dependency versions

- .github/workflows/nightly_ci_build.yml
- CHANGELOG.md
- Gemfile
- example_files/Gemfile
- example_files/mappers/Baseline.rb
- example_files/mappers/residential/template/util.rb
- example_files/mappers/residential/util.rb
- example_files/measures/BuildResidentialModel/measure.rb
- example_files/measures/BuildResidentialModel/tests/test_build_residential_model.rb
- lib/uo_cli.rb
- spec/uo_cli_spec.rb
> Prep 0.12.0

- example_files/python_deps/dependencies.json
Pick up version 0.8.0 of the [GMT](https://github.com/urbanopt/geojson-modelica-translator/releases) for additional functionality
> Use new version of GMT

- example_files/python_deps/dependencies.json
A new version of ThermalNetwork is available for use. This grabs it.
> Upgrade version of ThermalNetwork Python dependency

- CHANGELOG.md
- README.md
- lib/uo_cli/version.rb
New version to share with LadyBugTools that includes new GMT & TN versions
> Prep v0.14.0

- example_files/python_deps/dependencies.json
Pick up the newest version of the GMT
> Bump GMT to v0.9.3

- CMakeLists.txt
- scripts/setup-env.bat
This restores the windows .bat setup file.
> Add windows bat

- example_files/reopt/base_assumptions.json
- example_files/reopt/multiPV_assumptions.json
- spec/spec_files/reopt/base_assumptions.json
- spec/spec_files/reopt/multiPV_assumptions.json
We missed a change when updating to REopt v3. This update matches the current REopt v3 functionality.
> Update REopt assumptions files: `Storage` to `ElectricStorage`
