uo_cli.gemspec
Addresses #19 
Use Rack version that works with ruby 2.2
Set scenario & geojson gems as normal dependencies, not just dev deps.
=> Use Rack version that works with ruby 2.2

example_files/Gemfile
Addresses #40 
This is a quick fix for Windows users. **Not** intended to be the permanent solution!
Use Rack < 2.2 to work with Ruby 2.2. When we stop requiring Ruby 2.2 we can remove this requirement as well.
I expect Rack to only be used by github_api, a dev dependency. Why Windows users are requiring this for normal operation is not yet understood.
=> Add Rack dependency to enforce old version in example Gemfile

example_files/runner.conf
Config file was accidentally merged with settings still tweaked for testing. This restores the config settings to match the default values in openstudio-extension https://github.com/NREL/openstudio-extension-gem/blob/develop/lib/openstudio/extension/runner_config.rb#L75-L83
=> Restore config settings to default

lib/uo_cli.rb
Creates an empty base project folder when `-e` tag specified while creating project using `-p`. The project folder created does not include the feature file, weather files, and any openstudio models in osm_building.
=> Creates empty project folder

lib/uo_cli.rb
Adds -o tag to overwrite and replace with new project folder or with new empty project folder.
=> Overwrite project folder

lib/uo_cli.rb
- Add call to OpenDSS post-processor
- Remove `uo -a` call to post-processor
- Create `uo -g` call to post-processor
- Implement new `type` flag for users to specify which kind of post-processor they want to run. Will always run the default (kinda in the background), which the dss and reopt post-processors depend on.
=> Add DSS post-processor

lib/uo_cli.rb
- Add spacing to help text
- Recommend using absolute paths when making uo calls
- Reduces warnings that come when calling inside the project folder, using relative paths
=> Add spacing and recommend using absolute paths for commands

Gemfile, uo_cli.gemspec
Dependency on REopt needs to be in the gemspec file.
=> Put reopt dependency in gemspec, not Gemfile

lib/uo_cli.rb, spec/uo_cli_spec.rb
Simplify and improve error checking for user-input postprocessor types. Previously would not catch strings that included valid types plus more characters. It is now the way it should always have been done: simpler, and the postprocessor type must match exactly.
One issue I noticed that this doesn't fix: If the user enters `-t` and doesn't enter anything at all, the CLI throws an error that looks like it's coming from the `-s` call, which is incorrect. I'm not sure how to fix that. At least it still throws a graceful error, and the user can at least see that they did not enter anything after `-t`, even though they will be misled by the emphasis on `-s`.
=> REopt postprocessor error checking

lib/uo_cli.rb, spec/uo_cli_spec.rb
Adds a call to a new scenario-gem method during post-processing to save results as a db so they can be queried with sql.
For local testing, adjust Gemfile to point to the appropriate branch of scenario-gem until the new version is released (currently `db` branch). Jenkins postprocessing tests fail due to this.
=> add call to save scenario results in db file

lib/uo_cli.rb, spec/uo_cli_spec.rb, uo_cli.gemspec
Adds the ability to run opendss workflow with the CLI.  Checks that a suitable version of python is installed and that the urbanopt-ditto-reader package is installed.  Runs the python workflow directly from the CLI via the pycall gem.
=> Integrate ditto-reader/opendss into workflow

lib/uo_cli.rb
db file was only being created for default post-processing, not all types. This fixes that.
=> create db file for all postprocess types

lib/uo_cli.rb, spec/uo_cli_spec.rb
Makes saving to a db file optional with a flag in the CLI
=> Saving a database file is now optional

Gemfile, example_files/Gemfile, example_files/example_project.json, uo_cli.gemspec
Pin example_project gemfile dependencies `openstudio-common-measures` and `openstudio-model-articulation` to version 0.2.0. Version 0.2.1 included breaking changes that we'll adopt fairly soon, just not yet.
- Includes temporary gemspec/gemfile changes to point to scenario-gem branch that includes the same dependency changes as in the example_project gemfile here.
=> Pin dependencies

.gitignore, Gemfile, example_files/Gemfile, lib/uo_cli.rb, lib/uo_cli/version.rb, spec/spec_files/electrical_scenario.csv, spec/uo_cli_spec.rb, uo_cli.gemspec
Uses an installation of [ditto-reader](https://pypi.org/project/urbanopt-ditto-reader/) (which includes the cli for that repo) to make the `uo opendss` command work as expected. I'll repeat for the folks in the back: **ditto reader must be installed beforehand!** During testing, you must install from the `cli` branch of ditto-reader. If you install ditto-reader into a virtualenv (good practice), ensure that virtualenv is activated when you call `uo opendss`.
Also includes rspec tests, which for dev work should be excluded (change the test from `it 'does a thing' do...` to `xit 'does a thing' do...` for the test to run the electrical_network and to run opendss (lines 224 & 268, respectively). The only reason to exclude these tests is because it takes a long time to run a scenario of 13 …
=> Example files

lib/uo_cli.rb, spec/uo_cli_spec.rb
Quick bugfix for opendss timesteps
- Needed an additional set of quotes in the code for the quotes from the user to pass through.
=> bugfix for setting opendss timesteps

lib/uo_cli.rb, spec/uo_cli_spec.rb
Handle cases where user inputs wrong command, or none at all, after the `uo` entry
=> error handling when no/wrong commands given to cli

lib/uo_cli.rb, spec/uo_cli_spec.rb
Graceful error messages if invalid files passed to `uo create -s` command
=> error handling for create -s command

example_files/resources/hpxml-measures/Gemfile.lock
Old version of nokogiri had a security vulnerability. Turns out we don't use nokogiri, and doing a `bundle update` in the hpxml dir cleaned up that dependency.
=> update hpxml bundle

example_files/reopt/base_assumptions.json, example_files/reopt/multiPV_assumptions.json
Updates default PV assumptions to avoid future confusion
Uses average monthly energy and demand charges instead of specific rates
=> default PV assumtions so no system is automatically sized

lib/uo_cli.rb, spec/uo_cli_spec.rb
Adds `reopt-resilience` flag to `process` command, enabling resilience data in REopt optimizations
=> Reopt resilience

example_files/mappers/CreateBar.rb
When detailed model is present the create bar mapper skips create bar, create typical building measures
=> Fix create bar worklfow when detailed model is present

CMakeLists.txt
Updates installers to v0.7.1
Installers have been posted to: http://urbanopt-cli-installers.s3-website-us-west-2.amazonaws.com/?prefix=0.7.1/
=> Update installer 0.7.1

lib/uo_cli.rb
New cli option to set `num_parallel` in runner.conf from the cli. Useful for CI to use more cpus.
=> cli option for num_parallel (for devs/ci)

lib/uo_cli.rb, spec/uo_cli_spec.rb
The OpenDSS run cli command has additional arguments to indicate the start and end date of simulation. In the current implementation a user can indicate the start/end date as well as time. Adding the time argument separated by a space from the date was throwing an error in windows for an extra argument.
The start/end date and time are not added as separate arguments. There are passed on to the ditto cli, where they are combined before being added to the config file to run the simulation.
To test: 
pip install -e {local ditto reader repo on opendss_time_fix branch}
bundle exec uo opendss -s {path to scenario} -f {path to geojson} --start-date "2017/01/01" --start-time "01:00:00"--end-time "2017/01/02" --end-time "01:00:00"
=> Opendss time fix

spec/uo_cli_spec.rb
One opendss test had a tiny bug where the call to the opendss cli wasn't correct. This fixes it.
As long as the develop branch of ditto-reader is installed, this works (0.3.13 doesn't include this, so if the CI is using the released version it will still the test).
=> test bug: change underscore to dash to fix opendss test

lib/uo_cli.rb
Only copy assumptions files from cli to user's project-dir if the reopt folder doesn't exist.
=> bug: only copy assumptions files if the reopt folder did not exist

Gemfile, example_files/reopt/base_assumptions.json, example_files/reopt/multiPV_assumptions.json
Enable ability to tell reopt a min/max precent of renewables desired for the scenario, so it will return the optimal amount.
This populates existing fields in the reopt output. No new fields are created.
=> feat: add renewable min/max pct to reopt call

Gemfile, example_files/Gemfile, example_files/example_project.json, example_files/mappers/EvCharging.rb, example_files/mappers/base_workflow.osw
Adds argument to add_ev measure to use openstudio  model occupancy to determine number of EVs associated with a building feature
=> Add measure argument to use model occupancy for ev measure

example_files/mappers/Baseline.rb
Fixes #362 
Use feature index in geojson file instead of its ID for argument into BuildResidentialModel measure. The argument's type is set to integer and will error out when given a UUID
=> Fix for non-integer feature IDs and Residential workflow

CMakeLists.txt
This updates installers for v0.8.2. release.  New installer packages have been posted to http://urbanopt-cli-installers.s3-website-us-west-2.amazonaws.com/?prefix=0.8.2/
=> update to 0.8.2 version and bump gems

lib/uo_cli.rb
- When `num-parallel` flag is used with the `run` command, enforce that the value of num-parallel is an integer
- Switch priority so the `num-parallel` flag can be set to override the env var on a particular run
=> Num parallel bug

lib/uo_cli.rb, spec/uo_cli_spec.rb
- Adds update command to replace files in project directory with latest files in the example_files folder.
- To use, `bundle exec uo update --existing-project-folder (name of project folder) --new-project-directory (location of project directory)`
=> Update URBANopt Project

CMakeLists.txt
Updates for the 0.8.3 installer.  Installer packages have been posted to: http://urbanopt-cli-installers.s3-website-us-west-2.amazonaws.com/
=> update for 0.8.3 installers

CMakeLists.txt
Updating the installers to use v0.9.1.  They are now available at: http://urbanopt-cli-installers.s3-website-us-west-2.amazonaws.com/
=> update installers to 0.9.1

example_files/python_deps/dependencies.json, lib/uo_cli.rb
Be slightly less restrictive when running the `visualize` command to allow filetypes that end with `json` instead of only allowing `json` file type. For instance, now `*.geojson` is allowed.
=> allow geojson file type as well as json for feature files

CMakeLists.txt
Updates for the 0.9.3 installer packages.  These have been posted at: http://urbanopt-cli-installers.s3-website-us-west-2.amazonaws.com/
=> update installer for 0.9.3

.github/workflows/nightly_ci_build.yml, README.md
Add build status and test coverage badges for dependent urbanopt gems
On Github, review the Readme while on the [coverage-badges](https://github.com/urbanopt/urbanopt-cli/tree/coverage-badges) branch.
- Ensure that the badges
- display correctly
- link to the correct repos
- show the information we want to convey
=> Coverage badges

example_files/mappers/Baseline.rb, spec/uo_cli_spec.rb
Raise an informative error if the weatherfile is not able to match to a known climate zone. This happens if a user tries to use a non-US weather file, and may also catch other errors in the weather file.
~- [ ] Unit tests have been added or updated~
=> error handling for non-US weatherfiles

example_files/example_project_combined.json, example_files/mappers/Baseline.rb
Added geometry inputs for SFD units: 1) geometry orientation 2) geometry aspect ratio
=> Initial implementation of geometry orientation and aspect ratio

.github/workflows/nightly_ci_build.yml, example_files/mappers/Baseline.rb, example_files/python_deps/dependencies.json, lib/uo_cli/version.rb, spec/uo_cli_spec.rb, uo_cli.gemspec
- Separate tests into categories, so they can be run on different CI runners concurrently
- Set up a matrix for CI variations to run in parallel
- ~Test on Windows as well as Ubuntu~
- Fix warning about directory permissions from running a container on github-hosted CI
- Make non-US weather file error cleaner - no more stack trace!
- Apply bugfixes from ditto-reader
=> Categorize tests to parallelize CI

example_files/Gemfile
Some installations (maybe just Apple Silicon from the installer?) don't allow our bundle to install when using `https://rubygems.org` in the project_dir Gemfile. So we now default to using `http://rubygems.org` which is less secure but actually works.
=> use unsecured http as default rubygems source in project_dir

.github/workflows/nightly_ci_build.yml, lib/uo_cli.rb, spec/uo_cli_spec.rb
- We weren't calling the GMT-cli correctly which led to an erroneous error message when trying to `uo create_model`.
- The GMT-cli now works as intended, so we need tests for it! I made some.
- Added a new category of tests in CI to keep the parallelization going strong
=> Call GMT-cli correctly

example_files/python_deps/dependencies.json, lib/uo_cli.rb
ThermalNetwork version has been updated. We grab the newest patch version when we install, because we use tilde-version [here](https://github.com/urbanopt/urbanopt-cli/blob/develop/lib/uo_cli.rb#L1124). However, [this if statement](https://github.com/urbanopt/urbanopt-cli/blob/develop/lib/uo_cli.rb#L999-L1009) wants the version to match exactly, including patch version, so we output the "incorrect version" message. In this case, that's an erroneous message, but perhaps not always? During heavy development, I can imagine that sometimes the patch level could contain breaking changes. Or should we change the logic for that incorrect version message?
Decided to install exact dependency versions to eliminate this problem. In the distant future when versions are more stable we can revisit this.
=> Install exact python dependency versions, and bump ThermalNetwork version

lib/uo_cli.rb, spec/uo_cli_spec.rb
`des_params` & `des_create` had unnecessarily required input that was confusing the GMT cli. Removing the additional default input from here allows the GMT cli to apply its own default entries the way we expect.
=> Remove unnecessary default user-entry for DES commands

.github/workflows/nightly_ci_build.yml, example_files/python_deps/dependencies.json, example_files/python_deps/install_python.sh, lib/uo_cli.rb
- Use a new version of miniconda. The previous version had an older version of `pip` included which couldn't handle new python packaging standards. This resolves that issue.
- Use a new version of ThermalNetwork, to resolve the failing tests.
Since we set up miniconda, they have switched to date-version format, instead of semantic-version.
=> Upgrade miniconda

CHANGELOG.md, LICENSE.md, example_files/reopt/base_assumptions.json, example_files/reopt/multiPV_assumptions.json, lib/uo_cli/version.rb, spec/spec_files/reopt/base_assumptions.json, spec/spec_files/reopt/multiPV_assumptions.json
Reopt-api v3.11 contained a new requirement for the `year` field to be included in `ElectricLoad`. We addressed that in the reopt-gem with https://github.com/urbanopt/urbanopt-reopt-gem/pull/157, but mistakenly didn't make the same change here. This fixes that.
=> Update reopt assumptions file to work with REopt-api v3.11

example_files/python_deps/dependencies.json, lib/uo_cli.rb
- Change the direct dependency to be on urbanopt-des, which is the analysis tool for modelica models that have been built & simulated with the UO workflow.
- Maintains existing access, workflow, and commands for GMT
- Bumps GMT to v0.10.0, visible [in the des-output dependencies](https://github.com/urbanopt/urbanopt-des/blob/develop/pyproject.toml#L14)
TODO: Write new uo-cli commands that access this new functionality
=> Upgrade GMT version and expose urbanopt-des package
